/*  {
            "id": 0,
            "title": "DK7716 CNC WIRE CUT EDM",
            "model": "DK7716",
            "description": "CNC WIRE CUT EDM",
            "size": "big",
            "img": "DK7716CNCWIRECUTEDM",
        },
        {
            "id": 1,
            "title": "D71 DIE SINKER EDM",
            "model": "D71",
            "description": "D71 DIE SINKER EDM",
            "size": "big",
            "img": "D71DIESINKEREDM",
        }, {
            "id": 2,
            "title": "JZDX SERIES CNC CARVE-MILLING MACHINE",
            "model": "DX",
            "description": "JZDX SERIES CNC CARVE-MILLING MACHINE",
            "size": "big",
            "img": "JZDXSERIESCNCCARVE-MILLINGMACHINE",
        },*/

let jsonProducts = {
    "products": [
        {
            "id": 0,
            "title": "QT SERIES CNC ABRASIVE WIRE CUTTING MACHINE",
            "model": "QT56",
            "description": "QT SERIES CNC ABRASIVE WIRE CUTTING MACHINE",
            "size": "big",
            "img": "QTSERIESCNCABRASIVEWIRECUTTINGMACHINE",
        },
        {
            "id": 1,
            "title": "QT SERIES CNC ABRASIVE WIRE CUTTING MACHINE",
            "model": "QT56",
            "description": "QT SERIES CNC ABRASIVE WIRE CUTTING MACHINE",
            "size": "big",
            "img": "QTSERIESCNCABRASIVEWIRECUTTINGMACHINE2",
        },
        {
            "id": 2,
            "title": "XK SERIES CNC MACHINE CENTER",
            "model": "XH",
            "description": "XK SERIES CNC MACHINE CENTER",
            "size": "big",
            "img": "XKSERIESCNCMACHINECENTER",
        },
        {
            "id": 3,
            "title": "CNC MILLING MACHINE",
            "model": "XK",
            "description": "XK SERIES CNC MILLING MACHINE",
            "size": "big",
            "img": "CNCMILLINGMACHINE",
        },
        {
            "id": 4,
            "title": "DIE SNKER EDM WITH 3-AXIS",
            "model": "D71",
            "description": "DIE SNKER EDM WITH 3-AXIS",
            "size": "big",
            "img": "DIESNKEREDMWITH3-AXIS",
        },
        {
            "id": 5,
            "title": "DK7720 CNC WIRE EDM",
            "model": "DK7720",
            "description": "CNC WIRE CUT EDM",
            "size": "big",
            "img": "DK7720CNCWIREEDM",
        },
        {
            "id": 6,
            "title": "DK7725 CNC WIRE EDM",
            "model": "DK7725",
            "description": "CNC WIRE EDM",
            "size": "big",
            "img": "DK7725CNCWIREEDM",
        },
        {
            "id": 7,
            "title": "DK7732 CNC WIRE EDM",
            "model": "",
            "description": "CNC WIRE EDM",
            "size": "big",
            "img": "DK7732CNCWIREEDM",
        },
        {
            "id": 8,
            "title": "DK7740 CNC WIRE EDM",
            "model": "",
            "description": "CNC WIRE EDM",
            "size": "big",
            "img": "DK7740CNCWIREEDM",
        },
        {
            "id": 9,
            "title": "DK7755 CNC WIRE EDM",
            "model": "",
            "description": "CNC WIRE EDM",
            "size": "big",
            "img": "DK7755CNCWIREEDM",
        },
        {
            "id": 10,
            "title": "DK7763A CNC WIRE EDM",
            "model": "",
            "description": "CNC WIRE EDM",
            "size": "big",
            "img": "DK7763ACNCWIREEDM",
        },
        {
            "id": 11,
            "title": "DK7780 CNC WIRE EDM",
            "model": "",
            "description": "CNC WIRE EDM",
            "size": "big",
            "img": "DK7780CNCWIREEDM",
        },
        {
            "id": 12,
            "title": "DK771220 CNC WIRE EDM",
            "model": "",
            "description": "DK771220 CNC WIRE EDM",
            "size": "big",
            "img": "DK771220CNCWIREEDM",
        },
        {
            "id": 13,
            "title": "productx",
            "model": "Null",
            "description": "Sin Descripción",
            "size": "Null",
            "img": "productx",
        }
    ]
};
